# --------------------------------------------------------------
# TRAPPIST COMPILER - Makefile
# --------------------------------------------------------------

CC = gcc
CFLAGS = -O3 -Wall -Wextra -Wno-unused-function

# Pretty print colors
LEX_MSG     = printf "\033[1;36m[LEX]\033[0m     %s\n"
PARSE_MSG   = printf "\033[1;35m[PARSER]\033[0m  %s\n"
BC_MSG      = printf "\033[1;33m[BC]\033[0m      %s\n"
CORE_MSG    = printf "\033[1;32m[CORE]\033[0m    %s\n"
BUILD_MSG   = printf "\033[1;34m[BUILD]\033[0m   %s\n"

# --------------------------------------------------------------
# Source files grouped by subsystem
# --------------------------------------------------------------
LEXER_SRCS = lexer/front.c
PARSER_SRCS = parser/parser.c parser/reader.c
BC_SRCS = bytecode/bc.c
MAIN_SRC = trap.c

# Object files
OBJS = $(LEXER_SRCS:.c=.o) $(PARSER_SRCS:.c=.o) $(BC_SRCS:.c=.o) $(MAIN_SRC:.c=.o)

TARGET = trap

# --------------------------------------------------------------
# Default rule
# --------------------------------------------------------------
all: banner $(TARGET)

banner:
	@printf "\033[1;36m=== TRAPPIST COMPILER BUILD ===\033[0m\n"

# --------------------------------------------------------------
# Linking
# --------------------------------------------------------------
$(TARGET): $(OBJS)
	@$(BUILD_MSG) $(TARGET)
	@$(CC) $(CFLAGS) -o $(TARGET) $(OBJS)

# --------------------------------------------------------------
# Subsystem-specific compile rules
# --------------------------------------------------------------
lexer/%.o: lexer/%.c
	@$(LEX_MSG) $<
	@$(CC) $(CFLAGS) -c $< -o $@

parser/%.o: parser/%.c
	@$(PARSE_MSG) $<
	@$(CC) $(CFLAGS) -c $< -o $@

bytecode/%.o: bytecode/%.c
	@$(BC_MSG) $<
	@$(CC) $(CFLAGS) -c $< -o $@

%.o: %.c
	@$(CORE_MSG) $<
	@$(CC) $(CFLAGS) -c $< -o $@

# --------------------------------------------------------------
# Clean build artifacts
# --------------------------------------------------------------
clean:
	rm -f $(OBJS) $(TARGET)
	rm -f lexer/tok.le parser/c/code.ir codegen/out.trb

# --------------------------------------------------------------
# Full rebuild
# --------------------------------------------------------------
re: clean all

# --------------------------------------------------------------
# Run the compiler
# --------------------------------------------------------------
run: all
	./$(TARGET)
